name: Deploy Live

on:
  push:
    branches:
      - main   # deploys live site only on main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Configure Pages
      - uses: actions/configure-pages@v3

      # Upload site files artifact
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./   # root folder with index.html

      # Deploy to GitHub Pages
      - uses: actions/deploy-pages@v2
